set(_CATKIN_CURRENT_PACKAGE "transformation")
set(transformation_VERSION "0.0.0")
set(transformation_MAINTAINER "bertmuc <bertmuc@todo.todo>")
set(transformation_PACKAGE_FORMAT "2")
set(transformation_BUILD_DEPENDS "geometry_msgs" "quadrotor_msgs" "pcl_ros" "pcl_conversions" "airsim_ros_pkgs" "cv_bridge" "octomap_ros" "roscpp" "std_msgs" "sensor_msgs" "nav_msgs" "libpcl-all-dev")
set(transformation_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs" "std_msgs" "nav_msgs")
set(transformation_BUILDTOOL_DEPENDS "catkin")
set(transformation_BUILDTOOL_EXPORT_DEPENDS )
set(transformation_EXEC_DEPENDS "geometry_msgs" "quadrotor_msgs" "pcl_ros" "pcl_conversions" "airsim_ros_pkgs" "octomap_ros" "roscpp" "std_msgs" "nav_msgs" "sensor_msgs" "libpcl-all" "cv_bridge")
set(transformation_RUN_DEPENDS "geometry_msgs" "quadrotor_msgs" "pcl_ros" "pcl_conversions" "airsim_ros_pkgs" "octomap_ros" "roscpp" "std_msgs" "nav_msgs" "sensor_msgs" "libpcl-all" "cv_bridge")
set(transformation_TEST_DEPENDS )
set(transformation_DOC_DEPENDS )
set(transformation_URL_WEBSITE "")
set(transformation_URL_BUGTRACKER "")
set(transformation_URL_REPOSITORY "")
set(transformation_DEPRECATED "")