#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/bertmuc/SALLI/catkin_ws/devel_isolated/transformation:/home/bertmuc/SALLI/catkin_ws/devel_isolated/pointcloudTraj:/home/bertmuc/SALLI/catkin_ws/devel_isolated/odom_visualization:/home/bertmuc/SALLI/catkin_ws/devel_isolated/octomap:/home/bertmuc/SALLI/catkin_ws/devel_isolated/airsim_ros_pkgs:/home/bertmuc/SALLI/catkin_ws/devel_isolated/quadrotor_msgs:/home/bertmuc/SALLI/catkin_ws/devel_isolated/pose_utils:/home/bertmuc/SALLI/catkin_ws/devel_isolated/kdtree:/home/bertmuc/SALLI/catkin_ws/devel_isolated/catkin_simple:/opt/ros/noetic:/home/bertmuc/SALLI/catkin_ws/devel_isolated/sophus:/home/bertmuc/SALLI/catkin_ws/devel_isolated/sophus'
export LD_LIBRARY_PATH='/home/bertmuc/SALLI/catkin_ws/devel_isolated/pointcloudTraj/lib:/home/bertmuc/SALLI/catkin_ws/devel_isolated/odom_visualization/lib:/home/bertmuc/SALLI/catkin_ws/devel_isolated/octomap/lib:/home/bertmuc/SALLI/catkin_ws/devel_isolated/airsim_ros_pkgs/lib:/home/bertmuc/SALLI/catkin_ws/devel_isolated/quadrotor_msgs/lib:/home/bertmuc/SALLI/catkin_ws/devel_isolated/pose_utils/lib:/home/bertmuc/SALLI/catkin_ws/devel_isolated/kdtree/lib:/home/bertmuc/SALLI/catkin_ws/devel_isolated/catkin_simple/lib:/opt/ros/noetic/lib:/home/bertmuc/SALLI/catkin_ws/devel_isolated/sophus/lib:/home/bertmuc/SALLI/catkin_ws/devel_isolated/sophus/lib/x86_64-linux-gnu:/home/bertmuc/SALLI/catkin_ws/install_isolated/lib/mavlink_sitl_gazebo/plugins'
export PATH='/opt/ros/noetic/bin:/home/bertmuc/SALLI/catkin_ws/devel_isolated/sophus/bin:/opt/gcc-arm-none-eabi-9-2020-q2-update/bin:/home/bertmuc/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH='/home/bertmuc/SALLI/catkin_ws/devel_isolated/pointcloudTraj/lib/pkgconfig:/home/bertmuc/SALLI/catkin_ws/devel_isolated/odom_visualization/lib/pkgconfig:/home/bertmuc/SALLI/catkin_ws/devel_isolated/octomap/lib/pkgconfig:/home/bertmuc/SALLI/catkin_ws/devel_isolated/airsim_ros_pkgs/lib/pkgconfig:/home/bertmuc/SALLI/catkin_ws/devel_isolated/quadrotor_msgs/lib/pkgconfig:/home/bertmuc/SALLI/catkin_ws/devel_isolated/pose_utils/lib/pkgconfig:/home/bertmuc/SALLI/catkin_ws/devel_isolated/kdtree/lib/pkgconfig:/home/bertmuc/SALLI/catkin_ws/devel_isolated/catkin_simple/lib/pkgconfig:/opt/ros/noetic/lib/pkgconfig:/home/bertmuc/SALLI/catkin_ws/devel_isolated/sophus/lib/pkgconfig:/home/bertmuc/SALLI/catkin_ws/devel_isolated/sophus/lib/x86_64-linux-gnu/pkgconfig'
export PYTHONPATH='/home/bertmuc/SALLI/catkin_ws/devel_isolated/airsim_ros_pkgs/lib/python3/dist-packages:/home/bertmuc/SALLI/catkin_ws/devel_isolated/quadrotor_msgs/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages:/home/bertmuc/SALLI/catkin_ws/devel_isolated/sophus/lib/python3/dist-packages'
export ROSLISP_PACKAGE_DIRECTORIES="/home/bertmuc/SALLI/catkin_ws/devel_isolated/transformation/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/bertmuc/SALLI/catkin_ws/src/transformation:$ROS_PACKAGE_PATH"