set(_CATKIN_CURRENT_PACKAGE "vfh3d")
set(vfh3d_VERSION "0.0.0")
set(vfh3d_MAINTAINER "Saifullah <saifullah3396@gmail.com>")
set(vfh3d_PACKAGE_FORMAT "2")
set(vfh3d_BUILD_DEPENDS "octomap_msgs" "octomap_ros" "roscpp" "message_generation" "geometry_msgs")
set(vfh3d_BUILD_EXPORT_DEPENDS "octomap_msgs" "octomap_ros" "roscpp")
set(vfh3d_BUILDTOOL_DEPENDS "catkin")
set(vfh3d_BUILDTOOL_EXPORT_DEPENDS )
set(vfh3d_EXEC_DEPENDS "geometry_msgs" "octomap_msgs" "octomap_ros" "roscpp" "message_runtime")
set(vfh3d_RUN_DEPENDS "geometry_msgs" "octomap_msgs" "octomap_ros" "roscpp" "message_runtime")
set(vfh3d_TEST_DEPENDS )
set(vfh3d_DOC_DEPENDS )
set(vfh3d_URL_WEBSITE "")
set(vfh3d_URL_BUGTRACKER "")
set(vfh3d_URL_REPOSITORY "")
set(vfh3d_DEPRECATED "")