set(_CATKIN_CURRENT_PACKAGE "pointcloudTraj")
set(pointcloudTraj_VERSION "0.0.1")
set(pointcloudTraj_MAINTAINER "Fei Gao <fgaoaa@connect.ust.hk>")
set(pointcloudTraj_PACKAGE_FORMAT "1")
set(pointcloudTraj_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "kdtree" "quadrotor_msgs")
set(pointcloudTraj_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "kdtree" "quadrotor_msgs")
set(pointcloudTraj_BUILDTOOL_DEPENDS "catkin")
set(pointcloudTraj_BUILDTOOL_EXPORT_DEPENDS )
set(pointcloudTraj_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "kdtree" "quadrotor_msgs")
set(pointcloudTraj_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "kdtree" "quadrotor_msgs")
set(pointcloudTraj_TEST_DEPENDS )
set(pointcloudTraj_DOC_DEPENDS )
set(pointcloudTraj_URL_WEBSITE "")
set(pointcloudTraj_URL_BUGTRACKER "")
set(pointcloudTraj_URL_REPOSITORY "")
set(pointcloudTraj_DEPRECATED "")