set(_CATKIN_CURRENT_PACKAGE "octomap")
set(octomap_VERSION "0.0.0")
set(octomap_MAINTAINER "bertmuc <bertmuc@todo.todo>")
set(octomap_PACKAGE_FORMAT "2")
set(octomap_BUILD_DEPENDS "geometry_msgs" "quadrotor_msgs" "pcl_ros" "airsim_ros_pkgs" "cv_bridge" "octomap_ros" "roscpp" "std_msgs" "sensor_msgs" "nav_msgs" "libpcl-all-dev")
set(octomap_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs" "std_msgs" "nav_msgs")
set(octomap_BUILDTOOL_DEPENDS "catkin")
set(octomap_BUILDTOOL_EXPORT_DEPENDS )
set(octomap_EXEC_DEPENDS "geometry_msgs" "quadrotor_msgs" "pcl_ros" "airsim_ros_pkgs" "octomap_ros" "roscpp" "std_msgs" "nav_msgs" "sensor_msgs" "libpcl-all" "cv_bridge")
set(octomap_RUN_DEPENDS "geometry_msgs" "quadrotor_msgs" "pcl_ros" "airsim_ros_pkgs" "octomap_ros" "roscpp" "std_msgs" "nav_msgs" "sensor_msgs" "libpcl-all" "cv_bridge")
set(octomap_TEST_DEPENDS )
set(octomap_DOC_DEPENDS )
set(octomap_URL_WEBSITE "")
set(octomap_URL_BUGTRACKER "")
set(octomap_URL_REPOSITORY "")
set(octomap_DEPRECATED "")